// <auto-generated />
using System;
using InsurancesGAP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InsurancesGAP.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InsurancesGAP.Models.CoverageType", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CoverageType");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            Name = "Terremoto"
                        },
                        new
                        {
                            ID = 2L,
                            Name = "Incendio"
                        },
                        new
                        {
                            ID = 3L,
                            Name = "Robo"
                        },
                        new
                        {
                            ID = 4L,
                            Name = "Pérdida"
                        });
                });

            modelBuilder.Entity("InsurancesGAP.Models.Customer", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("InsurancesGAP.Models.Policy", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CoverageMonths")
                        .HasColumnType("int");

                    b.Property<double>("CoveragePercentage")
                        .HasColumnType("float");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<long>("RiskTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RiskTypeId");

                    b.ToTable("Policy");
                });

            modelBuilder.Entity("InsurancesGAP.Models.PolicyCoverageType", b =>
                {
                    b.Property<long>("CoverageTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("PolicyId")
                        .HasColumnType("bigint");

                    b.HasKey("CoverageTypeId", "PolicyId");

                    b.HasIndex("PolicyId");

                    b.ToTable("PolicyCoverageType");
                });

            modelBuilder.Entity("InsurancesGAP.Models.RiskType", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("RiskType");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            Name = "Bajo"
                        },
                        new
                        {
                            ID = 2L,
                            Name = "Medio"
                        },
                        new
                        {
                            ID = 3L,
                            Name = "Medio-Alto"
                        },
                        new
                        {
                            ID = 4L,
                            Name = "Alto"
                        });
                });

            modelBuilder.Entity("InsurancesGAP.Models.Policy", b =>
                {
                    b.HasOne("InsurancesGAP.Models.Customer", "Customer")
                        .WithMany("Policies")
                        .HasForeignKey("CustomerId");

                    b.HasOne("InsurancesGAP.Models.RiskType", "RiskType")
                        .WithMany("Policies")
                        .HasForeignKey("RiskTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InsurancesGAP.Models.PolicyCoverageType", b =>
                {
                    b.HasOne("InsurancesGAP.Models.CoverageType", "CoverageType")
                        .WithMany("PolicyCoverageTypes")
                        .HasForeignKey("CoverageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsurancesGAP.Models.Policy", "Policy")
                        .WithMany("PolicyCoverageTypes")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
